from database import SessionLocal, engine
from models import Base, Module, Level, TestCase, UserProgress, Submission
Base.metadata.create_all(bind=engine)

E, M, H = 'easy', 'medium', 'hard'

MODULES = [
  {"id":1,"name":"Variables","order_index":1,"theory":{"explanation":"Variables store data under a name. Use = to assign. Name on left, value on right.","examples":[{"label":"Easy","code":"x = 5\nprint(x)","output":"5"},{"label":"Medium","code":"a = 10\nb = a + 5\nprint(b)","output":"15"},{"label":"Hard","code":"a = 2\nb = a*3\nc = b-a\nprint(c)","output":"4"}]}},
  {"id":2,"name":"Print & Output","order_index":2,"theory":{"explanation":"print() displays output. f-strings embed variables: f'Hello {name}'. Use sep= to change the separator.","examples":[{"label":"Easy","code":"print('Hello World')","output":"Hello World"},{"label":"Medium","code":"name='Bob'\nprint(f'Hello {name}')","output":"Hello Bob"},{"label":"Hard","code":"item='Apple'\nprice=40\nprint(f'Item   : {item}')\nprint(f'Price  : {price}')","output":"Item   : Apple\nPrice  : 40"}]}},
  {"id":3,"name":"Data Types","order_index":3,"theory":{"explanation":"4 types: int, float, str, bool. Use type() to check. Convert with int(), float(), str().","examples":[{"label":"Easy","code":"print(type(5))","output":"<class 'int'>"},{"label":"Medium","code":"x='10'\nprint(int(x)+5)","output":"15"},{"label":"Hard","code":"n=7\nprint('Score: '+str(n*2))","output":"Score: 14"}]}},
  {"id":4,"name":"Arithmetic","order_index":4,"theory":{"explanation":"Operators: + - * / // (floor divide) % (remainder) ** (power). Follows BODMAS precedence.","examples":[{"label":"Easy","code":"print(3+7)","output":"10"},{"label":"Medium","code":"print(17//5)\nprint(17%5)","output":"3\n2"},{"label":"Hard","code":"r=7\nprint(round(3.14159*r**2,2))","output":"153.94"}]}},
  {"id":5,"name":"User Input","order_index":5,"theory":{"explanation":"input() reads text from user and always returns a string. Use int() or float() to convert for math.","examples":[{"label":"Easy","code":"name=input()\nprint('Hi',name)","output":"Hi Alice"},{"label":"Medium","code":"n=int(input())\nprint(n*2)","output":"10"},{"label":"Hard","code":"a=int(input())\nb=int(input())\nprint(a+b)","output":"12"}]}},
  {"id":6,"name":"Conditionals","order_index":6,"theory":{"explanation":"if/elif/else makes decisions. Operators: == != < > <= >=. Combine with and/or/not.","examples":[{"label":"Easy","code":"x=5\nif x>0:\n    print('Positive')","output":"Positive"},{"label":"Medium","code":"s=75\nif s>=90:\n    print('A')\nelif s>=70:\n    print('B')\nelse:\n    print('C')","output":"B"},{"label":"Hard","code":"age=20\nif 18<=age<65:\n    print('Adult')\nelse:\n    print('Other')","output":"Adult"}]}},
  {"id":7,"name":"Loops","order_index":7,"theory":{"explanation":"for i in range(n) repeats n times. while loops until False. break exits, continue skips.","examples":[{"label":"Easy","code":"for i in range(1,4):\n    print(i)","output":"1\n2\n3"},{"label":"Medium","code":"t=0\nfor i in range(1,5):\n    t+=i\nprint(t)","output":"10"},{"label":"Hard","code":"for i in range(1,6):\n    print(i*i)","output":"1\n4\n9\n16\n25"}]}},
  {"id":8,"name":"Strings","order_index":8,"theory":{"explanation":"Strings are text sequences. Index: s[0]. Slice: s[1:4]. Reverse: s[::-1]. Methods: .upper() .lower() .replace() .split() len().","examples":[{"label":"Easy","code":"print(len('hello'))","output":"5"},{"label":"Medium","code":"s='hello'\nprint(s[::-1])","output":"olleh"},{"label":"Hard","code":"s='I love cats'\nprint(s.replace('cats','***'))","output":"I love ***"}]}},
  {"id":9,"name":"Lists","order_index":9,"theory":{"explanation":"Lists are ordered collections []. Access by index, add with .append(), remove with .remove(), sort with .sort().","examples":[{"label":"Easy","code":"f=['apple','banana']\nprint(f[0])","output":"apple"},{"label":"Medium","code":"n=[3,1,2]\nn.sort()\nprint(n)","output":"[1, 2, 3]"},{"label":"Hard","code":"n=[10,20,30]\nprint(sum(n)/len(n))","output":"20.0"}]}},
  {"id":10,"name":"Dictionaries","order_index":10,"theory":{"explanation":"Dicts store key-value pairs {}. Access: d['key']. Update: d['key']=val. Loop: .items().","examples":[{"label":"Easy","code":"d={'name':'Alice'}\nprint(d['name'])","output":"Alice"},{"label":"Medium","code":"d={'a':1,'b':2}\nfor k,v in d.items():\n    print(k,v)","output":"a 1\nb 2"},{"label":"Hard","code":"ws=['hi','hi','bye']\nf={}\nfor w in ws:\n    f[w]=f.get(w,0)+1\nprint(f['hi'])","output":"2"}]}},
  {"id":11,"name":"Functions","order_index":11,"theory":{"explanation":"Functions group reusable code. Define with def, use parameters, return results. Default params make args optional.","examples":[{"label":"Easy","code":"def greet(n):\n    print('Hello',n)\ngreet('Alice')","output":"Hello Alice"},{"label":"Medium","code":"def add(a,b=10):\n    return a+b\nprint(add(5))","output":"15"},{"label":"Hard","code":"def stats(l):\n    return min(l),max(l)\nlo,hi=stats([3,1,5])\nprint(lo,hi)","output":"1 5"}]}},
]

# LEVELS and TESTS populated by seed_levels.py
CORE_LEVELS = [
  # ── MODULE 1: Variables ────────────────────────────────────
  {"id":1,"module_id":1,"order_index":1,"title":"Your First Variable","difficulty":E,"is_gate":False,
   "description":"Create a variable named x, assign the value 5 to it, and print it.",
   "starter_code":"# Create x here\n\n# Print x here\n","hints":["x = 5","print(x)"]},
  {"id":2,"module_id":1,"order_index":2,"title":"Three Variables","difficulty":E,"is_gate":False,
   "description":"Create: name = 'Alice', age = 25, city = 'Delhi'. Print each on a separate line.",
   "starter_code":"# Create the three variables\n\n# Print each\n","hints":["Use three separate print() calls"]},
  {"id":3,"module_id":1,"order_index":3,"title":"Reassign a Variable","difficulty":M,"is_gate":False,
   "description":"x starts as 10. Reassign it to x + 5. Print the new value.",
   "starter_code":"x = 10\n# Reassign x to x + 5\n\n# Print x\n","hints":["x = x + 5  or  x += 5"]},
  {"id":4,"module_id":1,"order_index":4,"title":"Swap Two Values","difficulty":M,"is_gate":False,
   "description":"a = 10 and b = 20 are given. Swap their values. Print a then b on separate lines.",
   "starter_code":"a = 10\nb = 20\n# Swap here\n\nprint(a)\nprint(b)\n","hints":["a, b = b, a"]},
  {"id":5,"module_id":1,"order_index":5,"title":"Variable Chain","difficulty":H,"is_gate":False,
   "description":"a = 2. Set b = a * 3. Set c = b - a. Print c.",
   "starter_code":"a = 2\n# Set b and c\n\n# Print c\n","hints":["b = a * 3  then  c = b - a"]},
  # ── MODULE 2: Print & Output ───────────────────────────────
  {"id":6,"module_id":2,"order_index":6,"title":"Say Hello","difficulty":E,"is_gate":False,
   "description":"Print exactly: Hello World",
   "starter_code":"# Print Hello World\n","hints":["print('Hello World')"]},
  {"id":7,"module_id":2,"order_index":7,"title":"Print Two Lines","difficulty":E,"is_gate":False,
   "description":"Print 'Hello' on the first line and 'World' on the second line.",
   "starter_code":"# Two print() calls\n","hints":["Use two separate print() statements"]},
  {"id":8,"module_id":2,"order_index":8,"title":"Custom Separator","difficulty":M,"is_gate":False,
   "description":"Print the values 10, 20, 30 on one line separated by ' - '. Expected: 10 - 20 - 30",
   "starter_code":"# Print with sep\n","hints":["print(10, 20, 30, sep=' - ')"]},
  {"id":9,"module_id":2,"order_index":9,"title":"F-String Sentence","difficulty":M,"is_gate":False,
   "description":"name = 'Alice' and age = 30 are given. Print: My name is Alice and I am 30 years old",
   "starter_code":"name = 'Alice'\nage = 30\n# Use an f-string\n","hints":["f'My name is {name} and I am {age} years old'"]},
  {"id":10,"module_id":2,"order_index":10,"title":"Formatted Receipt","difficulty":H,"is_gate":False,
   "description":"item = 'Apple' and price = 40. Print:\nItem   : Apple\nPrice  : 40",
   "starter_code":"item = 'Apple'\nprice = 40\n# Print formatted receipt\n","hints":["f'Item   : {item}'"]},
  # ── MODULE 3: Data Types ───────────────────────────────────
  {"id":11,"module_id":3,"order_index":11,"title":"Type of Integer","difficulty":E,"is_gate":False,
   "description":"Print the type of the number 5.",
   "starter_code":"# Print type of 5\n","hints":["print(type(5))"]},
  {"id":12,"module_id":3,"order_index":12,"title":"Type of String","difficulty":E,"is_gate":False,
   "description":"val = 'hello' is given. Print its type.",
   "starter_code":"val = 'hello'\n# Print type of val\n","hints":["print(type(val))"]},
  {"id":13,"module_id":3,"order_index":13,"title":"String to Integer","difficulty":M,"is_gate":False,
   "description":"s = '42' is given. Convert it to an integer, add 8, and print the result.",
   "starter_code":"s = '42'\n# Convert to int, add 8, print\n","hints":["int(s) converts the string"]},
  {"id":14,"module_id":3,"order_index":14,"title":"String to Float","difficulty":M,"is_gate":False,
   "description":"s = '3.14' is given. Convert to float, multiply by 2, and print.",
   "starter_code":"s = '3.14'\n# Convert to float, multiply by 2, print\n","hints":["float(s) converts the string"]},
  {"id":15,"module_id":3,"order_index":15,"title":"Number to String","difficulty":M,"is_gate":False,
   "description":"Concatenate the string 'Score: ' with the integer 99 and print the result.",
   "starter_code":"# Print 'Score: 99'\n","hints":["Use str(99) to convert first"]},
  {"id":16,"module_id":3,"order_index":16,"title":"Type Conversion Chain","difficulty":H,"is_gate":False,
   "description":"s = '7'. Convert to int, multiply by 3, convert to float, then print.",
   "starter_code":"s = '7'\n# Convert chain then print\n","hints":["int(s) → multiply → float(...)"]},
  # ── MODULE 4: Arithmetic ───────────────────────────────────
  {"id":17,"module_id":4,"order_index":17,"title":"Basic Addition","difficulty":E,"is_gate":False,
   "description":"Print the result of 3 + 7.",
   "starter_code":"# Print 3 + 7\n","hints":["print(3 + 7)"]},
  {"id":18,"module_id":4,"order_index":18,"title":"Floor and Remainder","difficulty":E,"is_gate":False,
   "description":"Print 17 // 5 on the first line, then 17 % 5 on the second line.",
   "starter_code":"# Print floor division then remainder\n","hints":["// is floor divide, % is remainder"]},
  {"id":19,"module_id":4,"order_index":19,"title":"Power Operator","difficulty":M,"is_gate":False,
   "description":"Read base then exponent from input. Print base raised to the power of exponent.",
   "starter_code":"# Read base and exponent\n\n# Print base ** exponent\n","hints":["Use ** for power"]},
  {"id":20,"module_id":4,"order_index":20,"title":"Rectangle Area","difficulty":M,"is_gate":False,
   "description":"Read length then width. Print the area of the rectangle.",
   "starter_code":"# Read length and width\n\n# Print area\n","hints":["area = length * width"]},
  {"id":21,"module_id":4,"order_index":21,"title":"Circle Area","difficulty":M,"is_gate":False,
   "description":"Read the radius. Print the circle area using pi=3.14159, rounded to 2 decimal places.",
   "starter_code":"pi = 3.14159\n# Read radius\n\n# Print area rounded to 2dp\n","hints":["area = pi * radius * radius","round(value, 2)"]},
  {"id":22,"module_id":4,"order_index":22,"title":"Temperature Converter","difficulty":H,"is_gate":False,
   "description":"Read a temperature in Celsius. Convert to Fahrenheit: F = (C * 9/5) + 32. Print the result.",
   "starter_code":"# Read Celsius\n\n# Convert and print Fahrenheit\n","hints":["F = (C * 9/5) + 32"]},
  # ── MODULE 5: User Input ───────────────────────────────────
  {"id":23,"module_id":5,"order_index":23,"title":"Greet User","difficulty":E,"is_gate":False,
   "description":"Read a name from input. Print: Hello [name]!",
   "starter_code":"# Read name\n\n# Print greeting\n","hints":["name = input()","print(f'Hello {name}!')"]},
  {"id":24,"module_id":5,"order_index":24,"title":"Double a Number","difficulty":E,"is_gate":False,
   "description":"Read an integer. Print it multiplied by 2.",
   "starter_code":"# Read integer\n\n# Print doubled\n","hints":["int(input()) to convert"]},
  {"id":25,"module_id":5,"order_index":25,"title":"Sum of Two Inputs","difficulty":M,"is_gate":False,
   "description":"Read two integers on separate lines. Print their sum.",
   "starter_code":"# Read a and b\n\n# Print sum\n","hints":["Convert each input with int()"]},
  {"id":26,"module_id":5,"order_index":26,"title":"Average of Three","difficulty":M,"is_gate":False,
   "description":"Read three numbers on separate lines. Print their average rounded to 2 decimal places.",
   "starter_code":"# Read three numbers\n\n# Print average (2dp)\n","hints":["average = (a + b + c) / 3","round(value, 2)"]},
  {"id":27,"module_id":5,"order_index":27,"title":"BMI Calculator","difficulty":H,"is_gate":False,
   "description":"Read weight in kg then height in m. Print BMI = weight / (height ** 2), rounded to 2 decimal places.",
   "starter_code":"# Read weight then height\n\n# Print BMI rounded to 2dp\n","hints":["bmi = weight / (height ** 2)"]},
  # ── MODULE 6: Conditionals ─────────────────────────────────
  {"id":28,"module_id":6,"order_index":28,"title":"Positive Check","difficulty":E,"is_gate":False,
   "description":"Read a number. Print 'Positive' if it is greater than 0, otherwise print 'Not Positive'.",
   "starter_code":"# Read number\n\n# Check positive\n","hints":["if num > 0:"]},
  {"id":29,"module_id":6,"order_index":29,"title":"Even or Odd","difficulty":E,"is_gate":False,
   "description":"Read an integer. Print 'Even' if divisible by 2, otherwise print 'Odd'.",
   "starter_code":"# Read number\n\n# Check even or odd\n","hints":["num % 2 == 0 means even"]},
  {"id":30,"module_id":6,"order_index":30,"title":"Grade Classifier","difficulty":M,"is_gate":False,
   "description":"Read a score. Print 'A' for >=90, 'B' for >=80, 'C' for >=70, 'F' for anything below.",
   "starter_code":"# Read score\n\n# Print grade\n","hints":["Use if/elif/elif/else"]},
  {"id":31,"module_id":6,"order_index":31,"title":"Leap Year","difficulty":M,"is_gate":False,
   "description":"Read a year. Print 'Leap' if it is a leap year, otherwise 'Not Leap'. A leap year is divisible by 4, but not 100, unless also divisible by 400.",
   "starter_code":"# Read year\n\n# Print Leap or Not Leap\n","hints":["Check: year%4==0 and (year%100!=0 or year%400==0)"]},
  {"id":32,"module_id":6,"order_index":32,"title":"Largest of Three","difficulty":M,"is_gate":False,
   "description":"Read three integers on separate lines. Print the largest.",
   "starter_code":"# Read three numbers\n\n# Print largest\n","hints":["Compare with if/elif/else"]},
  {"id":33,"module_id":6,"order_index":33,"title":"Age Category","difficulty":H,"is_gate":False,
   "description":"Read an age. Print 'Child' for <13, 'Teenager' for 13-17, 'Adult' for 18-64, 'Senior' for 65+.",
   "starter_code":"# Read age\n\n# Print category\n","hints":["Use if/elif/elif/else with range checks"]},
  {"id":34,"module_id":6,"order_index":34,"title":"Traffic Light","difficulty":H,"is_gate":False,
   "description":"Read a traffic light colour (red/yellow/green). Print the action: red=Stop, yellow=Slow Down, green=Go.",
   "starter_code":"# Read colour\n\n# Print action\n","hints":["Use if/elif/else to check colour"]},
  # ── MODULE 7: Loops ────────────────────────────────────────
  {"id":35,"module_id":7,"order_index":35,"title":"Count to N","difficulty":E,"is_gate":False,
   "description":"Read an integer N. Print all numbers from 1 to N on separate lines.",
   "starter_code":"# Read N\n\n# Print 1 to N\n","hints":["for i in range(1, N+1):"]},
  {"id":36,"module_id":7,"order_index":36,"title":"Countdown","difficulty":E,"is_gate":False,
   "description":"Read N. Print from N down to 1 on separate lines.",
   "starter_code":"# Read N\n\n# Print N down to 1\n","hints":["range(N, 0, -1) counts down"]},
  {"id":37,"module_id":7,"order_index":37,"title":"Sum 1 to N","difficulty":M,"is_gate":False,
   "description":"Read N. Print the sum of all numbers from 1 to N.",
   "starter_code":"# Read N\n\n# Calculate and print sum\n","hints":["total = 0, then add i in a loop"]},
  {"id":38,"module_id":7,"order_index":38,"title":"Multiplication Table","difficulty":M,"is_gate":False,
   "description":"Read N. Print its multiplication table from 1 to 10 in format: N x i = result",
   "starter_code":"# Read N\n\n# Print table\n","hints":["for i in range(1, 11):", "print(f'{N} x {i} = {N*i}')"]},
  {"id":39,"module_id":7,"order_index":39,"title":"Print Even Numbers","difficulty":M,"is_gate":False,
   "description":"Read N. Print all even numbers from 1 to N on separate lines.",
   "starter_code":"# Read N\n\n# Print evens\n","hints":["if i % 2 == 0: print(i)"]},
  {"id":40,"module_id":7,"order_index":40,"title":"Factorial","difficulty":H,"is_gate":False,
   "description":"Read N. Print N! (factorial). Note: 0! = 1.",
   "starter_code":"# Read N\n\n# Calculate factorial\n\n# Print result\n","hints":["result = 1, then multiply in a loop"]},
  {"id":41,"module_id":7,"order_index":41,"title":"FizzBuzz","difficulty":H,"is_gate":False,
   "description":"Read N. For 1 to N: print FizzBuzz if divisible by 3 and 5, Fizz if by 3, Buzz if by 5, else the number.",
   "starter_code":"# Read N\n\n# FizzBuzz loop\n","hints":["Check % 15 == 0 first for FizzBuzz"]},
  # ── MODULE 8: Strings ──────────────────────────────────────
  {"id":42,"module_id":8,"order_index":42,"title":"String Length","difficulty":E,"is_gate":False,
   "description":"Read a word. Print its length.",
   "starter_code":"# Read word\n\n# Print length\n","hints":["len(word)"]},
  {"id":43,"module_id":8,"order_index":43,"title":"Uppercase","difficulty":E,"is_gate":False,
   "description":"Read a sentence. Print it in all uppercase.",
   "starter_code":"# Read sentence\n\n# Print uppercase\n","hints":[".upper() converts to uppercase"]},
  {"id":44,"module_id":8,"order_index":44,"title":"Reverse a String","difficulty":M,"is_gate":False,
   "description":"Read a word. Print it reversed.",
   "starter_code":"# Read word\n\n# Print reversed\n","hints":["word[::-1] reverses a string"]},
  {"id":45,"module_id":8,"order_index":45,"title":"Count Vowels","difficulty":M,"is_gate":False,
   "description":"Read a word. Count and print the number of vowels (a, e, i, o, u — case insensitive).",
   "starter_code":"# Read word\n\n# Count vowels and print\n","hints":["if ch.lower() in 'aeiou':"]},
  {"id":46,"module_id":8,"order_index":46,"title":"Palindrome Check","difficulty":H,"is_gate":False,
   "description":"Read a word. Print 'Palindrome' if it reads the same forwards and backwards, else 'Not Palindrome'.",
   "starter_code":"# Read word\n\n# Check palindrome\n","hints":["word == word[::-1]"]},
  {"id":47,"module_id":8,"order_index":47,"title":"Replace a Word","difficulty":H,"is_gate":False,
   "description":"Read a sentence on line 1 and a word to censor on line 2. Replace all occurrences with *** and print.",
   "starter_code":"# Read sentence\n\n# Read word to censor\n\n# Print result\n","hints":["sentence.replace(word, '***')"]},
  # ── GATE ───────────────────────────────────────────────────
  {"id":48,"module_id":None,"order_index":48,"title":"Gate: Student Report Card","difficulty":H,"is_gate":True,
   "description":"Read a student's name, then 3 scores (Math, Science, English). Calculate average (2dp). Assign grade: A>=90, B>=80, C>=70, else F. Print:\nName: [name]\nAverage: [avg]\nGrade: [grade]",
   "starter_code":"# Read name\n\n# Read 3 scores\n\n# Calculate average\n\n# Determine grade\n\n# Print results\n",
   "hints":[]},
]
BRIDGE_LEVELS = [
  # ── MODULE 9: Lists ────────────────────────────────────────
  {"id":49,"module_id":9,"order_index":49,"title":"Print Each Fruit","difficulty":E,"is_gate":False,
   "description":"A list of 5 fruits is given. Print each fruit on a separate line.",
   "starter_code":"fruits = ['apple', 'banana', 'cherry', 'mango', 'grape']\n# Print each fruit\n",
   "hints":["Use a for loop: for fruit in fruits:"]},
  {"id":50,"module_id":9,"order_index":50,"title":"First and Last","difficulty":E,"is_gate":False,
   "description":"nums = [10, 20, 30, 40, 50] is given. Print the first item, then the last item.",
   "starter_code":"nums = [10, 20, 30, 40, 50]\n# Print first item\n\n# Print last item\n",
   "hints":["nums[0] for first, nums[-1] for last"]},
  {"id":51,"module_id":9,"order_index":51,"title":"Append and Remove","difficulty":M,"is_gate":False,
   "description":"fruits = ['apple', 'banana', 'cherry'] is given. Add 'mango' to the end, remove 'banana'. Print each remaining item on a separate line.",
   "starter_code":"fruits = ['apple', 'banana', 'cherry']\n# Add mango\n\n# Remove banana\n\n# Print each fruit\n",
   "hints":["fruits.append('mango')", "fruits.remove('banana')"]},
  {"id":52,"module_id":9,"order_index":52,"title":"List Sum and Average","difficulty":M,"is_gate":False,
   "description":"Read 5 integers (one per line). Print their sum on the first line and average (2 decimal places) on the second line.",
   "starter_code":"nums = []\n# Read 5 integers and add to nums\n\n# Print sum then average\n",
   "hints":["Use a for loop 5 times", "round(avg, 2)"]},
  {"id":53,"module_id":9,"order_index":53,"title":"Sort a List","difficulty":M,"is_gate":False,
   "description":"Read 5 integers (one per line). Print them sorted in ascending order, one per line.",
   "starter_code":"nums = []\n# Read 5 integers\n\n# Sort and print each\n",
   "hints":["nums.sort() then loop to print"]},
  {"id":54,"module_id":9,"order_index":54,"title":"Find Max Manually","difficulty":H,"is_gate":False,
   "description":"Read 5 integers (one per line). Find and print the maximum value without using the built-in max() function.",
   "starter_code":"nums = []\n# Read 5 integers\n\n# Find max manually and print\n",
   "hints":["Start with highest = nums[0], then compare each"]},
  # ── MODULE 10: Dictionaries ────────────────────────────────
  {"id":55,"module_id":10,"order_index":55,"title":"Create and Access Dict","difficulty":E,"is_gate":False,
   "description":"person = {'name': 'Alice', 'age': 25, 'city': 'Delhi'} is given. Print name, then age, then city on separate lines.",
   "starter_code":"person = {'name': 'Alice', 'age': 25, 'city': 'Delhi'}\n# Print name, age, city\n",
   "hints":["person['name'] accesses a value"]},
  {"id":56,"module_id":10,"order_index":56,"title":"Print All Keys","difficulty":E,"is_gate":False,
   "description":"data = {'a': 1, 'b': 2, 'c': 3} is given. Print each key on a separate line.",
   "starter_code":"data = {'a': 1, 'b': 2, 'c': 3}\n# Print each key\n",
   "hints":["for key in data:  or  for key in data.keys():"]},
  {"id":57,"module_id":10,"order_index":57,"title":"Update a Value","difficulty":M,"is_gate":False,
   "description":"student = {'name': 'Bob', 'grade': 'B'} is given. Update 'grade' to 'A'. Print the updated grade.",
   "starter_code":"student = {'name': 'Bob', 'grade': 'B'}\n# Update grade to 'A'\n\n# Print updated grade\n",
   "hints":["student['grade'] = 'A'"]},
  {"id":58,"module_id":10,"order_index":58,"title":"Key Exists Check","difficulty":M,"is_gate":False,
   "description":"user = {'name': 'Alice', 'email': 'alice@example.com'} is given. Check if 'phone' key exists. Print 'Yes' or 'No'.",
   "starter_code":"user = {'name': 'Alice', 'email': 'alice@example.com'}\n# Check if 'phone' exists\n",
   "hints":["if 'phone' in user:"]},
  {"id":59,"module_id":10,"order_index":59,"title":"Word Frequency","difficulty":H,"is_gate":False,
   "description":"Read a sentence. Count how many times each word appears. Print each word and its count in alphabetical order (format: 'word count').",
   "starter_code":"# Read sentence\n\n# Count word frequency\n\n# Print sorted by word\n",
   "hints":["freq[w] = freq.get(w, 0) + 1", "for w in sorted(freq):"]},
  {"id":60,"module_id":10,"order_index":60,"title":"Invert a Dictionary","difficulty":H,"is_gate":False,
   "description":"d = {'x': 1, 'y': 2, 'z': 3} is given. Swap its keys and values. Print each pair as 'key value' sorted by the new key.",
   "starter_code":"d = {'x': 1, 'y': 2, 'z': 3}\n# Invert keys and values\n\n# Print sorted by new key\n",
   "hints":["inverted = {v: k for k, v in d.items()}"]},
  # ── MODULE 11: Functions ───────────────────────────────────
  {"id":61,"module_id":11,"order_index":61,"title":"Greet Function","difficulty":E,"is_gate":False,
   "description":"Write a function greet(name) that prints 'Hello [name]!'. Read a name from input and call it.",
   "starter_code":"def greet(name):\n    # Print Hello [name]!\n    pass\n\n# Read name and call greet\n",
   "hints":["print(f'Hello {name}!')"]},
  {"id":62,"module_id":11,"order_index":62,"title":"Add Function","difficulty":E,"is_gate":False,
   "description":"Write a function add(a, b) that returns the sum. Read two integers and print add(a, b).",
   "starter_code":"def add(a, b):\n    # Return sum\n    pass\n\n# Read a and b, print result\n",
   "hints":["return a + b"]},
  {"id":63,"module_id":11,"order_index":63,"title":"Square Function","difficulty":M,"is_gate":False,
   "description":"Write a function square(n) that returns n squared. Read an integer and print square(n).",
   "starter_code":"def square(n):\n    # Return n squared\n    pass\n\n# Read n, print square(n)\n",
   "hints":["return n * n  or  n ** 2"]},
  {"id":64,"module_id":11,"order_index":64,"title":"Max of Three","difficulty":M,"is_gate":False,
   "description":"Write a function max_of_three(a, b, c) that returns the largest. Read three integers and print the result.",
   "starter_code":"def max_of_three(a, b, c):\n    # Return the largest\n    pass\n\n# Read three numbers, print result\n",
   "hints":["Use if/elif/else to compare all three"]},
  {"id":65,"module_id":11,"order_index":65,"title":"Is Even Function","difficulty":M,"is_gate":False,
   "description":"Write a function is_even(n) that returns True if n is even, False otherwise. Read an integer and print the result.",
   "starter_code":"def is_even(n):\n    # Return True or False\n    pass\n\n# Read n, print is_even(n)\n",
   "hints":["return n % 2 == 0"]},
  {"id":66,"module_id":11,"order_index":66,"title":"Factorial Function","difficulty":H,"is_gate":False,
   "description":"Write a function factorial(n) that returns n! using a loop. Read an integer and print factorial(n).",
   "starter_code":"def factorial(n):\n    # Calculate n! using a loop\n    pass\n\n# Read n, print factorial(n)\n",
   "hints":["result = 1, then multiply i in range(1, n+1)"]},
  {"id":67,"module_id":11,"order_index":67,"title":"Min and Max Function","difficulty":H,"is_gate":False,
   "description":"Write a function min_max(nums) that returns a tuple (min, max). Read 5 integers and print the min then the max.",
   "starter_code":"def min_max(nums):\n    # Return (min_val, max_val)\n    pass\n\n# Read 5 integers into a list\nnums = []\n# Call min_max and print results\n",
   "hints":["Return (min(nums), max(nums))  — or find manually"]},
]
CORE_TESTS = [
  # Mod 1: Variables
  {"level_id":1,"stdin":"","expected_output":"5\n","is_hidden":False},
  {"level_id":2,"stdin":"","expected_output":"Alice\n25\nDelhi\n","is_hidden":False},
  {"level_id":3,"stdin":"","expected_output":"15\n","is_hidden":False},
  {"level_id":4,"stdin":"","expected_output":"20\n10\n","is_hidden":False},
  {"level_id":5,"stdin":"","expected_output":"4\n","is_hidden":False},
  # Mod 2: Print & Output
  {"level_id":6,"stdin":"","expected_output":"Hello World\n","is_hidden":False},
  {"level_id":7,"stdin":"","expected_output":"Hello\nWorld\n","is_hidden":False},
  {"level_id":8,"stdin":"","expected_output":"10 - 20 - 30\n","is_hidden":False},
  {"level_id":9,"stdin":"","expected_output":"My name is Alice and I am 30 years old\n","is_hidden":False},
  {"level_id":10,"stdin":"","expected_output":"Item   : Apple\nPrice  : 40\n","is_hidden":False},
  # Mod 3: Data Types
  {"level_id":11,"stdin":"","expected_output":"<class 'int'>\n","is_hidden":False},
  {"level_id":12,"stdin":"","expected_output":"<class 'str'>\n","is_hidden":False},
  {"level_id":13,"stdin":"","expected_output":"50\n","is_hidden":False},
  {"level_id":14,"stdin":"","expected_output":"6.28\n","is_hidden":False},
  {"level_id":15,"stdin":"","expected_output":"Score: 99\n","is_hidden":False},
  {"level_id":16,"stdin":"","expected_output":"21.0\n","is_hidden":False},
  # Mod 4: Arithmetic
  {"level_id":17,"stdin":"","expected_output":"10\n","is_hidden":False},
  {"level_id":18,"stdin":"","expected_output":"3\n2\n","is_hidden":False},
  {"level_id":19,"stdin":"2\n3\n","expected_output":"8\n","is_hidden":False},
  {"level_id":19,"stdin":"5\n2\n","expected_output":"25\n","is_hidden":True},
  {"level_id":20,"stdin":"5\n4\n","expected_output":"20\n","is_hidden":False},
  {"level_id":20,"stdin":"10\n3\n","expected_output":"30\n","is_hidden":True},
  {"level_id":21,"stdin":"7\n","expected_output":"153.94\n","is_hidden":False},
  {"level_id":21,"stdin":"5\n","expected_output":"78.54\n","is_hidden":True},
  {"level_id":22,"stdin":"0\n","expected_output":"32.0\n","is_hidden":False},
  {"level_id":22,"stdin":"100\n","expected_output":"212.0\n","is_hidden":True},
  # Mod 5: User Input
  {"level_id":23,"stdin":"Bob\n","expected_output":"Hello Bob!\n","is_hidden":False},
  {"level_id":23,"stdin":"Alice\n","expected_output":"Hello Alice!\n","is_hidden":True},
  {"level_id":24,"stdin":"5\n","expected_output":"10\n","is_hidden":False},
  {"level_id":24,"stdin":"13\n","expected_output":"26\n","is_hidden":True},
  {"level_id":25,"stdin":"5\n7\n","expected_output":"12\n","is_hidden":False},
  {"level_id":25,"stdin":"100\n200\n","expected_output":"300\n","is_hidden":True},
  {"level_id":26,"stdin":"10\n20\n30\n","expected_output":"20.0\n","is_hidden":False},
  {"level_id":26,"stdin":"1\n2\n4\n","expected_output":"2.33\n","is_hidden":True},
  {"level_id":27,"stdin":"70\n1.75\n","expected_output":"22.86\n","is_hidden":False},
  {"level_id":27,"stdin":"90\n1.8\n","expected_output":"27.78\n","is_hidden":True},
  # Mod 6: Conditionals
  {"level_id":28,"stdin":"5\n","expected_output":"Positive\n","is_hidden":False},
  {"level_id":28,"stdin":"-3\n","expected_output":"Not Positive\n","is_hidden":True},
  {"level_id":29,"stdin":"4\n","expected_output":"Even\n","is_hidden":False},
  {"level_id":29,"stdin":"7\n","expected_output":"Odd\n","is_hidden":True},
  {"level_id":30,"stdin":"95\n","expected_output":"A\n","is_hidden":False},
  {"level_id":30,"stdin":"55\n","expected_output":"F\n","is_hidden":True},
  {"level_id":31,"stdin":"2024\n","expected_output":"Leap\n","is_hidden":False},
  {"level_id":31,"stdin":"1900\n","expected_output":"Not Leap\n","is_hidden":True},
  {"level_id":32,"stdin":"3\n7\n5\n","expected_output":"7\n","is_hidden":False},
  {"level_id":32,"stdin":"15\n3\n9\n","expected_output":"15\n","is_hidden":True},
  {"level_id":33,"stdin":"8\n","expected_output":"Child\n","is_hidden":False},
  {"level_id":33,"stdin":"70\n","expected_output":"Senior\n","is_hidden":True},
  {"level_id":34,"stdin":"red\n","expected_output":"Stop\n","is_hidden":False},
  {"level_id":34,"stdin":"green\n","expected_output":"Go\n","is_hidden":True},
  # Mod 7: Loops
  {"level_id":35,"stdin":"3\n","expected_output":"1\n2\n3\n","is_hidden":False},
  {"level_id":35,"stdin":"5\n","expected_output":"1\n2\n3\n4\n5\n","is_hidden":True},
  {"level_id":36,"stdin":"3\n","expected_output":"3\n2\n1\n","is_hidden":False},
  {"level_id":36,"stdin":"5\n","expected_output":"5\n4\n3\n2\n1\n","is_hidden":True},
  {"level_id":37,"stdin":"4\n","expected_output":"10\n","is_hidden":False},
  {"level_id":37,"stdin":"10\n","expected_output":"55\n","is_hidden":True},
  {"level_id":38,"stdin":"3\n","expected_output":"3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27\n3 x 10 = 30\n","is_hidden":False},
  {"level_id":39,"stdin":"6\n","expected_output":"2\n4\n6\n","is_hidden":False},
  {"level_id":39,"stdin":"10\n","expected_output":"2\n4\n6\n8\n10\n","is_hidden":True},
  {"level_id":40,"stdin":"5\n","expected_output":"120\n","is_hidden":False},
  {"level_id":40,"stdin":"7\n","expected_output":"5040\n","is_hidden":True},
  {"level_id":41,"stdin":"15\n","expected_output":"1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n","is_hidden":False},
  # Mod 8: Strings
  {"level_id":42,"stdin":"hello\n","expected_output":"5\n","is_hidden":False},
  {"level_id":42,"stdin":"python\n","expected_output":"6\n","is_hidden":True},
  {"level_id":43,"stdin":"hello world\n","expected_output":"HELLO WORLD\n","is_hidden":False},
  {"level_id":43,"stdin":"python is fun\n","expected_output":"PYTHON IS FUN\n","is_hidden":True},
  {"level_id":44,"stdin":"hello\n","expected_output":"olleh\n","is_hidden":False},
  {"level_id":44,"stdin":"python\n","expected_output":"nohtyp\n","is_hidden":True},
  {"level_id":45,"stdin":"hello\n","expected_output":"2\n","is_hidden":False},
  {"level_id":45,"stdin":"Python\n","expected_output":"1\n","is_hidden":True},
  {"level_id":46,"stdin":"racecar\n","expected_output":"Palindrome\n","is_hidden":False},
  {"level_id":46,"stdin":"hello\n","expected_output":"Not Palindrome\n","is_hidden":True},
  {"level_id":47,"stdin":"I love cats and cats love me\ncats\n","expected_output":"I love *** and *** love me\n","is_hidden":False},
  {"level_id":47,"stdin":"hello world hello\nhello\n","expected_output":"*** world ***\n","is_hidden":True},
  # Gate
  {"level_id":48,"stdin":"Alice\n95\n85\n90\n","expected_output":"Name: Alice\nAverage: 90.0\nGrade: A\n","is_hidden":True},
  {"level_id":48,"stdin":"Bob\n70\n65\n75\n","expected_output":"Name: Bob\nAverage: 70.0\nGrade: C\n","is_hidden":True},
  {"level_id":48,"stdin":"Carol\n50\n40\n60\n","expected_output":"Name: Carol\nAverage: 50.0\nGrade: F\n","is_hidden":True},
  {"level_id":48,"stdin":"David\n80\n88\n84\n","expected_output":"Name: David\nAverage: 84.0\nGrade: B\n","is_hidden":True},
]
BRIDGE_TESTS = [
  # Mod 9: Lists
  {"level_id":49,"stdin":"","expected_output":"apple\nbanana\ncherry\nmango\ngrape\n","is_hidden":False},
  {"level_id":50,"stdin":"","expected_output":"10\n50\n","is_hidden":False},
  {"level_id":51,"stdin":"","expected_output":"apple\ncherry\nmango\n","is_hidden":False},
  {"level_id":52,"stdin":"10\n20\n30\n40\n50\n","expected_output":"150\n30.0\n","is_hidden":False},
  {"level_id":52,"stdin":"1\n2\n3\n4\n5\n","expected_output":"15\n3.0\n","is_hidden":True},
  {"level_id":53,"stdin":"3\n1\n4\n1\n5\n","expected_output":"1\n1\n3\n4\n5\n","is_hidden":False},
  {"level_id":53,"stdin":"9\n2\n7\n4\n6\n","expected_output":"2\n4\n6\n7\n9\n","is_hidden":True},
  {"level_id":54,"stdin":"3\n7\n2\n9\n1\n","expected_output":"9\n","is_hidden":False},
  {"level_id":54,"stdin":"15\n3\n27\n8\n12\n","expected_output":"27\n","is_hidden":True},
  # Mod 10: Dicts
  {"level_id":55,"stdin":"","expected_output":"Alice\n25\nDelhi\n","is_hidden":False},
  {"level_id":56,"stdin":"","expected_output":"a\nb\nc\n","is_hidden":False},
  {"level_id":57,"stdin":"","expected_output":"A\n","is_hidden":False},
  {"level_id":58,"stdin":"","expected_output":"No\n","is_hidden":False},
  {"level_id":59,"stdin":"hi hi bye\n","expected_output":"bye 1\nhi 2\n","is_hidden":False},
  {"level_id":59,"stdin":"the cat sat on the mat\n","expected_output":"cat 1\nmat 1\non 1\nsat 1\nthe 2\n","is_hidden":True},
  {"level_id":60,"stdin":"","expected_output":"1 x\n2 y\n3 z\n","is_hidden":False},
  # Mod 11: Functions
  {"level_id":61,"stdin":"Alice\n","expected_output":"Hello Alice!\n","is_hidden":False},
  {"level_id":61,"stdin":"Bob\n","expected_output":"Hello Bob!\n","is_hidden":True},
  {"level_id":62,"stdin":"3\n5\n","expected_output":"8\n","is_hidden":False},
  {"level_id":62,"stdin":"10\n20\n","expected_output":"30\n","is_hidden":True},
  {"level_id":63,"stdin":"7\n","expected_output":"49\n","is_hidden":False},
  {"level_id":63,"stdin":"9\n","expected_output":"81\n","is_hidden":True},
  {"level_id":64,"stdin":"3\n7\n5\n","expected_output":"7\n","is_hidden":False},
  {"level_id":64,"stdin":"15\n3\n9\n","expected_output":"15\n","is_hidden":True},
  {"level_id":65,"stdin":"4\n","expected_output":"True\n","is_hidden":False},
  {"level_id":65,"stdin":"7\n","expected_output":"False\n","is_hidden":True},
  {"level_id":66,"stdin":"5\n","expected_output":"120\n","is_hidden":False},
  {"level_id":66,"stdin":"7\n","expected_output":"5040\n","is_hidden":True},
  {"level_id":67,"stdin":"3\n1\n4\n1\n5\n","expected_output":"1\n5\n","is_hidden":False},
  {"level_id":67,"stdin":"9\n2\n7\n4\n6\n","expected_output":"2\n9\n","is_hidden":True},
]

LEVELS = CORE_LEVELS + BRIDGE_LEVELS
TESTS  = CORE_TESTS  + BRIDGE_TESTS

def seed():
    db = SessionLocal()
    try:
        for cls in [Submission, TestCase, UserProgress, Level, Module]:
            db.query(cls).delete()
        db.commit()
        for m in MODULES: db.add(Module(**m))
        db.commit()
        for lv in LEVELS: db.add(Level(**lv))
        db.commit()
        for t in TESTS: db.add(TestCase(**t))
        db.commit()
        all_levels = db.query(Level).order_by(Level.order_index).all()
        for i, lv in enumerate(all_levels):
            db.add(UserProgress(user_id="guest", level_id=lv.id,
                                status="unlocked" if i == 0 else "locked"))
        db.commit()
        print(f"Seeded: {len(LEVELS)} levels, {len(TESTS)} test cases")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
